### ISSUE TITLE
API not logging in

### ISSUE THREAD

**Issue by hardikchhajar** [algo2t/alphatrade#51]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): alpha.sasonline.in:443
DEBUG:urllib3.connectionpool:https://alpha.sasonline.in:443 "GET /api/v2/profile HTTP/1.1" 401 61
DEBUG:urllib3.connectionpool:https://alpha.sasonline.in:443 "POST /api/v2/login HTTP/1.1" 200 144
DEBUG:urllib3.connectionpool:https://alpha.sasonline.in:443 "POST /api/v2/checktwofa HTTP/1.1" 500 45
Traceback (most recent call last):
  File "c:\Users\Ganpati\Desktop\SAS\config.py", line 12, in <module>
    sas = AlphaTrade(login_id=login_id, password=password, twofa=pin)
  File "C:\Users\Ganpati\AppData\Local\Programs\Python\Python310\lib\site-packages\alphatrade\alphatrade.py", line 240, in __init__
    self.__set_access_token()
  File "C:\Users\Ganpati\AppData\Local\Programs\Python\Python310\lib\site-packages\alphatrade\alphatrade.py", line 309, in __set_access_token
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"errors":{"detail":"Internal server error"}}

**Comment by hardikchhajar** [comment]
Traceback (most recent call last):
  File "c:\Users\Ganpati\Desktop\SAS\config.py", line 12, in <module>
    sas = AlphaTrade(login_id=login_id, password=password, twofa=pin)
  File "C:\Users\Ganpati\AppData\Local\Programs\Python\Python310\lib\site-packages\alphatrade\alphatrade.py", line 240, in __init__
    self.__set_access_token()
  File "C:\Users\Ganpati\AppData\Local\Programs\Python\Python310\lib\site-packages\alphatrade\alphatrade.py", line 309, in __set_access_token
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"errors":{"detail":"Internal server error"}}

**Comment by nevatia** [comment]
Please send ur telegram id

**Comment by bhaskarndas** [comment]
Even I am also facing the same issue

**Comment by bhaskarndas** [comment]
my telegram_id bhaskarndas

**Comment by DaXAce** [comment]
Hi @bhaskarndas , is your issue resolved? 
i am still facing issue...
@nevatia , how to resolve this? my telegram id is @DaXAce ...

**Comment by nevatia** [comment]
https://t.me/sasonlineunofficial join here

**Comment by algo2t** [comment]
Closing this issue as it is not reproducible for me. I have already worked on Linux and Windows both. Make sure you try to install the latest version v1.0.0 and see if login works. Do not forget to go through the README
